### ISSUE TITLE
Lisibilité du « i » en h4

### ISSUE THREAD

**Issue by notabene** [Paris-Web/24jdw#30]
Salut @ffoodd !

j'ai un affichage de « i»  pas très joyeux avec le Raleway sur les `h4` sous Windows 11 (FF et Edge rendent pareil), cf. saisie d'écran ci-dessous, dans l'article [« Avez-vous pensé à iel ? »](https://www.24joursdeweb.fr/2024/avez-vous-pense-a-iel-ou-limpact-de-lecriture-inclusive-sur-les-personnes-dyslexiques).
L'espace du point disparaît, ça rend la lecture difficile (puisqu'on en parle 😉).

Exemple sur `.post-entry > h4:nth-child(35)`

![Capture d'écran 2024-12-11 100520](https://github.com/user-attachments/assets/81e44315-68f3-4dbf-89a8-f4fcb8bb6e06)

**Comment by ffoodd** [comment]
On a un vrai sujet sur la lisibilité, la Georgia paraît très petite à beaucoup de monde. On va creuser ça :)

**Comment by ffoodd** [comment]
C’est en cours de correction, sur un autre dépôt : je fais du ménage ici :)
